export const MODEL_NAME_WIDTH = '3.5rem'
export const inputPaddingRight = 'calc(var(--space-2) + var(--space-2) + var(--space-2))'

export const SAMPLES = [
	'The UK Department of Transport',
	'The St. Louis Merchants',
	'The Green Bay Packers',
	'The Czech second city Brno',
	'Australia coach Geoff Marsh',
	'Polish brewer Zywiec',
	'South African Breweries Ltd',
	'Czech President Vaclav Havel',
	'Trade and Industry Secretary Ian Lang',
	'The London-to-Boston route',
	'British Prime Minister John Major’s office',
	'New York Commodities Desk',
	'The London Stock Exchange',
	'PaineWebber analyst Marc Cohen',
	'New York Stock Exchange',
	'The elected Bangui government',
	'Polish-born Pope John Paul',
	'East Timorese-born activist Jose Ramos Horta',
	'The Indonesian ambassador to Norway',
	"Suu Kyi's National League for Democracy",
	'Canadian Grain Commission',
	'Chicago Board of Trade',
]
export const HMM_PREDICTIONS = [
	['O', 'B-ORG', 'I-ORG', 'O', 'O'],
	['O', 'B-ORG', 'O', 'B-ORG', 'I-ORG', 'I-ORG'],
	['O', 'B-PER', 'I-PER', 'O'],
	['O', 'B-LOC', 'O', 'O', 'O'],
	['B-LOC', 'O', 'B-PER', 'I-PER'],
	['B-MISC', 'I-MISC', 'I-MISC'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['B-LOC', 'O', 'B-PER', 'I-PER'],
	['O', 'O', 'O', 'O', 'B-PER', 'I-PER'],
	['O', 'B-LOC', 'O', 'O', 'O', 'B-LOC', 'O'],
	['B-MISC', 'O', 'O', 'B-PER', 'I-PER', 'O', 'O', 'O'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['O', 'B-ORG', 'I-ORG', 'I-ORG'],
	['B-ORG', 'O', 'B-PER', 'I-PER'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['O', 'O', 'O', 'O'],
	['B-MISC', 'O', 'O', 'O', 'B-PER', 'I-PER'],
	['B-ORG', 'I-ORG', 'O', 'O', 'O', 'B-PER', 'I-PER', 'O'],
	['O', 'B-MISC', 'O', 'O', 'B-LOC'],
	['B-PER', 'I-PER', 'O', 'B-MISC', 'I-MISC', 'O', 'O'],
	['B-ORG', 'I-ORG', 'I-ORG'],
	['B-ORG', 'I-ORG', 'O', 'O'],
]
export const MEMM_PREDICTIONS = [
	['O', 'B-LOC', 'I-LOC', 'I-LOC', 'I-LOC'],
	['O', 'B-ORG', 'O', 'O', 'B-PER', 'I-PER'],
	['O', 'B-PER', 'I-PER', 'I-PER'],
	['O', 'B-LOC', 'O', 'O', 'B-PER'],
	['B-LOC', 'O', 'B-PER', 'I-PER'],
	['B-MISC', 'O', 'O'],
	['B-MISC', 'I-MISC', 'I-MISC', 'I-MISC'],
	['B-LOC', 'O', 'B-PER', 'I-PER'],
	['O', 'O', 'O', 'O', 'B-PER', 'I-PER'],
	['O', 'B-LOC', 'O', 'O', 'O', 'B-LOC', 'O'],
	['B-MISC', 'O', 'O', 'B-PER', 'I-PER', 'O', 'O', 'O'],
	['B-LOC', 'I-LOC', 'I-LOC', 'I-LOC'],
	['O', 'B-LOC', 'I-LOC', 'I-LOC'],
	['O', 'O', 'B-PER', 'I-PER'],
	['B-LOC', 'I-LOC', 'I-LOC', 'I-LOC'],
	['O', 'O', 'B-LOC', 'O'],
	['B-MISC', 'O', 'O', 'B-PER', 'I-PER', 'I-PER'],
	['B-ORG', 'I-ORG', 'O', 'O', 'O', 'B-PER', 'I-PER', 'I-PER'],
	['O', 'B-MISC', 'O', 'O', 'B-LOC'],
	['O', 'O', 'O', 'B-ORG', 'I-ORG', 'O', 'O'],
	['B-ORG', 'I-ORG', 'I-ORG'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
]
export const CRF_PREDICTIONS = [
	['O', 'B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['O', 'B-ORG', 'O', 'O', 'B-PER', 'I-PER'],
	['O', 'B-ORG', 'I-ORG', 'I-ORG'],
	['O', 'B-MISC', 'O', 'O', 'O'],
	['B-LOC', 'O', 'B-PER', 'I-PER'],
	['B-MISC', 'O', 'B-ORG'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['B-MISC', 'O', 'B-PER', 'I-PER'],
	['O', 'O', 'O', 'O', 'B-PER', 'I-PER'],
	['O', 'B-LOC', 'O', 'O', 'O', 'B-ORG', 'O'],
	['B-MISC', 'O', 'O', 'B-PER', 'I-PER', 'O', 'O', 'O'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['O', 'B-ORG', 'I-ORG', 'I-ORG'],
	['O', 'O', 'B-PER', 'I-PER'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['O', 'O', 'B-ORG', 'O'],
	['B-MISC', 'O', 'O', 'B-PER', 'I-PER', 'I-PER'],
	['B-LOC', 'I-LOC', 'O', 'O', 'O', 'B-PER', 'I-PER', 'I-PER'],
	['O', 'B-MISC', 'O', 'O', 'B-LOC'],
	['B-PER', 'I-PER', 'O', 'B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
	['B-ORG', 'I-ORG', 'I-ORG'],
	['B-ORG', 'I-ORG', 'I-ORG', 'I-ORG'],
]
